//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorDeSenha.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.servicoSoap")]
    public interface servicoSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento CriarSenhaResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CriarSenha", ReplyAction="*")]
        GeradorDeSenha.ServiceReference1.CriarSenhaResponse CriarSenha(GeradorDeSenha.ServiceReference1.CriarSenhaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CriarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<GeradorDeSenha.ServiceReference1.CriarSenhaResponse> CriarSenhaAsync(GeradorDeSenha.ServiceReference1.CriarSenhaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarSenhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriarSenha", Namespace="http://tempuri.org/", Order=0)]
        public GeradorDeSenha.ServiceReference1.CriarSenhaRequestBody Body;
        
        public CriarSenhaRequest() {
        }
        
        public CriarSenhaRequest(GeradorDeSenha.ServiceReference1.CriarSenhaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CriarSenhaRequestBody {
        
        public CriarSenhaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarSenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriarSenhaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GeradorDeSenha.ServiceReference1.CriarSenhaResponseBody Body;
        
        public CriarSenhaResponse() {
        }
        
        public CriarSenhaResponse(GeradorDeSenha.ServiceReference1.CriarSenhaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CriarSenhaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CriarSenhaResult;
        
        public CriarSenhaResponseBody() {
        }
        
        public CriarSenhaResponseBody(string CriarSenhaResult) {
            this.CriarSenhaResult = CriarSenhaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicoSoapChannel : GeradorDeSenha.ServiceReference1.servicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicoSoapClient : System.ServiceModel.ClientBase<GeradorDeSenha.ServiceReference1.servicoSoap>, GeradorDeSenha.ServiceReference1.servicoSoap {
        
        public servicoSoapClient() {
        }
        
        public servicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeradorDeSenha.ServiceReference1.CriarSenhaResponse GeradorDeSenha.ServiceReference1.servicoSoap.CriarSenha(GeradorDeSenha.ServiceReference1.CriarSenhaRequest request) {
            return base.Channel.CriarSenha(request);
        }
        
        public string CriarSenha() {
            GeradorDeSenha.ServiceReference1.CriarSenhaRequest inValue = new GeradorDeSenha.ServiceReference1.CriarSenhaRequest();
            inValue.Body = new GeradorDeSenha.ServiceReference1.CriarSenhaRequestBody();
            GeradorDeSenha.ServiceReference1.CriarSenhaResponse retVal = ((GeradorDeSenha.ServiceReference1.servicoSoap)(this)).CriarSenha(inValue);
            return retVal.Body.CriarSenhaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeradorDeSenha.ServiceReference1.CriarSenhaResponse> GeradorDeSenha.ServiceReference1.servicoSoap.CriarSenhaAsync(GeradorDeSenha.ServiceReference1.CriarSenhaRequest request) {
            return base.Channel.CriarSenhaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeradorDeSenha.ServiceReference1.CriarSenhaResponse> CriarSenhaAsync() {
            GeradorDeSenha.ServiceReference1.CriarSenhaRequest inValue = new GeradorDeSenha.ServiceReference1.CriarSenhaRequest();
            inValue.Body = new GeradorDeSenha.ServiceReference1.CriarSenhaRequestBody();
            return ((GeradorDeSenha.ServiceReference1.servicoSoap)(this)).CriarSenhaAsync(inValue);
        }
    }
}
